version: '3'
services:
  app:
    build: .
    restart: always
    tty: true
    image: app
    container_name: app
    volumes:
      - ./app:/go/src
    ports:
      - "3150:3150"
    depends_on:
      - "db"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306

volumes:
  db-data:
    driver: local